config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  root 'home#index'
  resources :maquinas
  resources :home
  resources :contato
  resources :sobre
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/maquina.rb
class Maquina < ApplicationRecord

    validates :nome, length: { minimum: 2, maximum: 80 }
    validates :descricao, length: { maximum: 1000 }
    validates :garantia, numericality: { only_integer: true }
    
    validate:checar_data

    def checar_data
        if (self.compra > Date.today)
        errors.add(:compra, ": A data de compra não pode estar no futuro")
        end
    end
    
   before_destroy :checar_tempo_limite

    def checar_tempo_limite
       
       if (self.created_at + 30.minutes > Time.zone.now)
        errors.add(:created_at, ": Uma máquina não pode ser removida se ela foi criada há mais de 30 minutos")
        end  
        errors.present?
    end
end
    

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def after_sign_in_path_for(resource)
        '/maquinas'
    end

    def after_sign_up_path_for(resource)
        '/maquinas'
    end

end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/maquinas_controller.rb
class MaquinasController < ApplicationController
  before_action :set_maquina, only: %i[ show edit update destroy ]

  # GET /maquinas or /maquinas.json
  def index
    @maquinas = Maquina.all
  end

  # GET /maquinas/1 or /maquinas/1.json
  def show
  end

  # GET /maquinas/new
  def new
    @maquina = Maquina.new
  end

  # GET /maquinas/1/edit
  def edit
  end

  # POST /maquinas or /maquinas.json
  def create
    @maquina = Maquina.new(maquina_params)

    respond_to do |format|
      if @maquina.save
        format.html { redirect_to @maquina, notice: "Máquina criada com sucesso." }
        format.json { render :show, status: :created, location: @maquina }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maquina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maquinas/1 or /maquinas/1.json
  def update
    respond_to do |format|
      if @maquina.update(maquina_params)
        format.html { redirect_to @maquina, notice: "Máquina alterada com sucesso." }
        format.json { render :show, status: :ok, location: @maquina }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maquina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maquinas/1 or /maquinas/1.json
  def destroy
    @maquina.destroy
    respond_to do |format|
      format.html { redirect_to maquinas_url, notice: "Máquina excluída com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maquina
      @maquina = Maquina.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maquina_params
      params.require(:maquina).permit(:tipo, :nome, :descricao, :garantia, :compra, :quebrada)
    end
end

app/controllers/sobre_controller.rb
class SobreController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maquinas_helper.rb
module MaquinasHelper
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/views/contato/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title>How To Create Bootstrap 5 Header With Login Form Design</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://www.markuptag.com/bootstrap/5/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Fira+Sans+Extra+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Heebo:wght@100;200;300;400;500;600;700;800;900&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');

:root {
    --font1: 'Heebo', sans-serif;
    --font2: 'Fira Sans Extra Condensed', sans-serif;
    --font3: 'Roboto', sans-serif
}

body {
    font-family: var(--font3);
    background-image: linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%)
}

h2 {
    font-weight: 900
}

.container-fluid {
    max-width: 1200px
}


.btn {
    font-size: 1rem;
    font-weight: 500;
    text-transform: uppercase;
    padding: 5px 50px 5px 50px
}

.box .btn {
    font-size: 1.5rem
}

@media (max-width: 1025px) {
    .btn {
        padding: 5px 40px 5px 40px
    }
}

@media (max-width: 250px) {
    .btn {
        padding: 5px 30px 5px 30px
    }
}

.btn-warning {
    background: none #f7810a;
    color: #ffffff;
    fill: #ffffff;
    border: none;
    text-decoration: none;
    outline: 0;
    box-shadow: -1px 6px 19px rgba(247, 129, 10, 0.25);
    border-radius: 100px
}

.btn-warning:hover {
    background: none #ff962b;
    color: #ffffff;
    box-shadow: -1px 6px 13px rgba(255, 150, 43, 0.35)
}

.price-hp {
    font-size: 1rem;
    font-weight: 600;
    color: darkgray
}
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/home"><h2 class="text-warning">RoadMáquinas</h2></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mob-navbar" aria-label="Toggle">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mob-navbar">
                <ul class="navbar-nav mb-2 mb-lg-0 mx-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/home">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/sobre">SOBRE NÓS</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">MÁQUINAS</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Máquinas Industriais</a></li>
                            <li><a class="dropdown-item" href="#">Equipamentos</a></li>
                            <li><a class="dropdown-item" href="/maquinas">Acessórios</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="#">Explore Mais</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contato">CONTATO</a>
                    </li>
                </ul>
                <form class="d-flex">
                    
                    <%= link_to 'Login', new_usuario_session_path, class:"btn btn-warning"  %> 
                    <%= link_to 'Cadastrar', new_usuario_registration_path, class:"btn btn-warning" %> 

                </form>
            </div>
        </div>
    </nav>

    <!-- Bootstrap JS -->
    <script src="https://www.markuptag.com/bootstrap/5/js/bootstrap.bundle.min.js"></script>
    <main>
    <!--Section: Contact v.2-->
    <section class="mb-5">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contate-nos</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Você tem alguma pergunta? Por favor, não hesite em nos contatar diretamente. Nossa equipe entrará em contato com você em questão de horas para ajudá-lo.</p>

    <div class="row pl-5">

        <!--Grid column-->
        <div class="col-md-8 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Seu nome</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Seu email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Sua menssagem</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-warning" onclick="document.getElementById('contact-form').submit();">Enviar</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>R. do Bom Jesus, 125 - Recife </p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>(81) 99991-4471 </p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>contato@roadmaquinas.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->
</main>
</body>

     <footer class="row bg-secondary text-white py-4 mt-auto">
        <div class="container p-5 pb-0">
                <!-- Section: Links -->
                <section>
                  <!--Grid row-->
                  <div class="row">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-3 col-xl-3 mx-auto ">
                      <h6 class="text-uppercase mb-4 font-weight-bold">
                        RoadMáquinas
                      </h6>
                      <p>
                      Diversas soluções em máquinas industriais para diversos segmentos de mercado. 
                      
                      </p>
                    </div>
                    <!-- Grid column -->

                    <hr class="w-100 clearfix d-md-none" />

                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto">
                      <h6 class="text-uppercase mb-4 font-weight-bold" href="#">LINHA DE ​MÁQUINAS</h6>
                      <p>
                        <a class="text-white">- Empacotadoras</a><br>
                        <a class="text-white">- Enfardadoras</a><br>
                        <a class="text-white">- Encaixotadoras</a><br>
                        <a class="text-white">- Dosadores</a><br>
                      </p>             
                    </div>
                    <!-- Grid column -->

                    <hr class="w-100 clearfix d-md-none" />

                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto ">
                      <h6 class="text-uppercase mb-4 font-weight-bold">
                        NOSSOS HORÁRIOS
                      </h6>
                      <p>
                        <a class="text-white">Segunda a Sexta, das 08:00 às 18:00h.</a>
                      </p>
                   
                  
                    </div>

                    <!-- Grid column -->
                    <hr class="w-100 clearfix d-md-none" />

                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto ">
                      <h6 class="text-uppercase mb-4 font-weight-bold">Contato</h6>
                      <p><i class="fas fa-home mr-3"></i> R. do Bom Jesus, 125 - Recife </p>
                      <p><i class="fas fa-phone mr-3"></i></i> Telefone: (81) 99991-4471 </p>  
                        <a class="btn btn-outline-light btn-floating " class="text-white" role="button" href="https://www.rdmapps.com.br/">
                        <i class="fas fa-building"></i> </a>

                      <!-- GitHub -->
                      <a class="btn btn-outline-light btn-floating text-white" role="button" href="https://github.com/lucianapacheco" >
                        <i class="fab fa-github"> </i>
                      </a>
                    </div>
                    <!-- Grid column -->
                  </div>
                  <!--Grid row-->
                </section>
              </div>
     </footer>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoadMaquinas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maquinas/edit.html.erb
<style> 
 
  .maquinas {
    position: relative;
    width: 100%;
    float: right;
    height: 100vh;
    
    .container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100%;
    }
  }
  .principal{
    text-align: center;
    position: absolute;
    margin-top: 35px;
    width:100%
  }
  .show_maquina{
    display: inline-block;
    position: relative;
    height: 493px;
    width:60%
  }
a:link, a:visited {
	text-decoration: none;
  color:white
	}

</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

<div class="container-fluid overflow-hidden">
    <div class="row vh-100 overflow-auto">
        <div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-dark d-flex sticky-top">
            <div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
                <a href="/" class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
                </a>
                <div>
                <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item" style="font-size: 20px">
                        <a class="nav-link px-sm-0 px-2">
                            <a href="/maquinas"><span class="ms-1 d-none d-sm-inline">Máquinas</span></a>
                        </a>
                    </li>
                    <li class="nav-item" style="font-size: 20px">
                        <a class="nav-link px-sm-0 px-2">
                            <a><%= link_to 'Sair', destroy_usuario_session_path, method: :delete %> <span class="ms-1 d-none d-sm-inline"></span></a>
                        </a>
                    </li>
                </ul>
                </div>
            </div>
        </div>
        
        <div class="col d-flex flex-column h-sm-100">
          <main class="row overflow-auto">
            <div class="col pt-4">
              <section class="maquinas">
                <div class="principal">
                  <div class="show_maquina">
                  <h1>Alterar Máquina</h1>
                  <%= render 'form', maquina: @maquina %>
                  <br>
                  <%= link_to 'Visualizar', @maquina, class:"btn btn-success" %> 
                  <%= link_to 'Voltar', maquinas_path, class:"btn btn-info" %> 
                  </div>
              </section>
            </div>
          </main>
        </div>
  </div>
</div>







  

app/views/maquinas/index.html.erb
<style>
a:link, a:visited {
	text-decoration: none;
  color:white
	}
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

<div class="container-fluid overflow-hidden">
  <div class="row vh-100 overflow-auto">
    <div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-dark d-flex sticky-top">
      <div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
        <a href="/" class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none"></a>
        <div>
          <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
            <li class="nav-item" style="font-size: 20px">
              <a class="nav-link px-sm-0 px-2">
                 <a href="/maquinas"><span class="ms-1 d-none d-sm-inline">Máquinas</span></a>
              </a>
            </li>
             <li class="nav-item" style="font-size: 20px">
                <a class="nav-link px-sm-0 px-2">
                 <a><%= link_to 'Sair', destroy_usuario_session_path, method: :delete %> <span class="ms-1 d-none d-sm-inline"></span></a>
              </a>
            </li>
          </ul>
      </div>
  </div>
</div>

<div class="col d-flex flex-column h-sm-100">
  <main class="row overflow-auto">
    <div class="col pt-4">
      <p id="notice"><%= notice %></p>

        <h1>Máquinas</h1>

      <table class="table table-striped">
      <thead>
      <tr>
      <th>Tipo</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Meses de garantia</th>
      <th>Data da compra</th>
      <th>Quebrada</th>
      <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @maquinas.each do |maquina| %>
      <tr>
      <td><%= maquina.tipo %></td>
      <td><%= maquina.nome %></td>
      <td><%= maquina.descricao %></td>
      <td><%= maquina.garantia %></td>
      <td><%= maquina.compra %></td>
      <td> <%= maquina.quebrada %></td>

      <td> <%= link_to 'Visualizar', maquina, class:"btn btn-success" %></td> 
      <td> <%= link_to 'Alterar', edit_maquina_path(maquina), class:"btn btn-warning" %></td> 
      <td> <%= link_to 'Remover', maquina, method: :delete, data: { confirm: 'Tem certeza que deseja remover?' }, class:"btn btn-danger" %></td> 

      </tr>
      <% end %>
      </tbody>
      </table>
    <br>

    <%= link_to 'Adicionar Máquina', new_maquina_path, class:"btn btn-primary mb-4"  %> 
    </div>
</main>

<footer class="row bg-secondary text-white py-4 mt-auto">
  <div class="container p-5 pb-0">
  <!-- Section: Links -->
    <section>
    <!--Grid row-->
      <div class="row">
      <!-- Grid column -->
        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto ">
          <h6 class="text-uppercase mb-4 font-weight-bold">
          RoadMáquinas </h6>
          <p>  Diversas soluções em máquinas industriais para diversos segmentos de mercado.  </p>
        </div>
        <!-- Grid column -->

         <hr class="w-100 clearfix d-md-none" />

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto">
        <h6 class="text-uppercase mb-4 font-weight-bold" href="#">LINHA DE ​MÁQUINAS</h6>
          <p>
            <a class="text-white">- Empacotadoras</a><br>
            <a class="text-white">- Enfardadoras</a><br>
            <a class="text-white">- Encaixotadoras</a><br>
            <a class="text-white">- Dosadores</a><br>
          </p>             
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none" />

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto ">
        <h6 class="text-uppercase mb-4 font-weight-bold">
        NOSSOS HORÁRIOS
        </h6>
        <p>
        <a class="text-white">Segunda a Sexta, das 08:00 às 18:00h.</a>
        </p>
      </div>

      <!-- Grid column -->
      <hr class="w-100 clearfix d-md-none" />

      <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto ">
          <h6 class="text-uppercase mb-4 font-weight-bold">Contato</h6>
          <p><i class="fas fa-home mr-3"></i> R. do Bom Jesus, 125 - Recife </p>
          <p><i class="fas fa-phone mr-3"></i></i> Telefone: (81) 99991-4471 </p>  
          <a class="btn btn-outline-light btn-floating " class="text-white" role="button" href="https://www.rdmapps.com.br/">
          <i class="fas fa-building"></i> </a>

          <!-- GitHub -->
          <a class="btn btn-outline-light btn-floating text-white" role="button" href="https://github.com/lucianapacheco" >
          <i class="fab fa-github"> </i>
          </a>
        </div>
      <!-- Grid column -->
      </div>
      <!--Grid row-->
    </section>
  </div>
</footer>
</div>
</div>
</div>

app/views/maquinas/new.html.erb
<style> 
 
  .maquinas {
    position: relative;
    width: 100%;
    float: right;
    height: 100vh;
    
    .container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100%;
    }
  }
  .principal{
    text-align: center;
    position: absolute;
    margin-top: 35px;
    width:100%
  }
  .show_maquina{
    display: inline-block;
    position: relative;
    height: 493px;
    width:60%
  }

a:link, a:visited {
	text-decoration: none;
  color:white
	}

</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

<div class="container-fluid overflow-hidden">
    <div class="row vh-100 overflow-auto">
        <div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-dark d-flex sticky-top">
            <div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
                <a href="/" class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
                </a>
                <div>
                <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item" style="font-size: 20px">
                        <a class="nav-link px-sm-0 px-2">
                            <a href="/maquinas"><span class="ms-1 d-none d-sm-inline">Máquinas</span></a>
                        </a>
                    </li>
                    <li class="nav-item" style="font-size: 20px">
                        <a class="nav-link px-sm-0 px-2">
                            <a><%= link_to 'Sair', destroy_usuario_session_path, method: :delete %> <span class="ms-1 d-none d-sm-inline"></span></a>
                        </a>
                    </li>
                </ul>
                </div>
            </div>
        </div>

        <div class="col d-flex flex-column h-sm-100">
          <main class="row overflow-auto">
            <div class="col pt-4">
              <section class="maquinas">
                <div class="principal">
                  <div class="show_maquina">
                  <h1>Nova Máquina</h1>

                    <%= render 'form', maquina: @maquina %>
                    <br>
                    <%= link_to 'Voltar', maquinas_path, class:"btn btn-info" %> 
                  </div>
              </section>
            </div>
          </main>
        </div>
  </div>
</div>

app/views/maquinas/show.html.erb
<style> 
 
  .maquinas {
    position: relative;
    width: 100%;
    float: right;
    height: 100vh;
    
    .container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100%;
    }
  }
  .principal{
    text-align: center;
    position: absolute;
    margin-top: 35px;
    width:100%
  }
  .show_maquina{
    display: inline-block;
    position: relative;
    height: 493px;
    width:60%
  }
a:link, a:visited {
	text-decoration: none;
  color:white
	}

</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

<div class="container-fluid overflow-hidden">
    <div class="row vh-100 overflow-auto">
        <div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-dark d-flex sticky-top">
            <div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
                <a href="/" class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
                </a>
                <div>
                <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item" style="font-size: 20px">
                        <a class="nav-link px-sm-0 px-2">
                            <a href="/maquinas"><span class="ms-1 d-none d-sm-inline">Máquinas</span></a>
                        </a>
                    </li>
                    <li class="nav-item" style="font-size: 20px">
                        <a class="nav-link px-sm-0 px-2">
                            <a><%= link_to 'Sair', destroy_usuario_session_path, method: :delete %> <span class="ms-1 d-none d-sm-inline"></span></a>
                        </a>
                    </li>
                </ul>
                </div>
            </div>
        </div>

        <div class="col d-flex flex-column h-sm-100">
            <main class="row overflow-auto">
                <div class="col pt-4">
                    <section class="maquinas">
                        <div class="principal">
                            <div class="show_maquina">
                                <p>
                                <strong>Tipo:</strong>
                                <%= @maquina.tipo %>
                                </p>
                                <p>
                                <strong>Nome:</strong>
                                <%= @maquina.nome %>
                                </p>
                                <p>
                                <strong>Descri&ccedil;&atilde;o:</strong>
                                <%= @maquina.descricao %>
                                </p>
                                <p>
                                <strong>Garantia:</strong>
                                <%= @maquina.garantia %>
                                </p>
                                <p>
                                <strong>Compra:</strong>
                                <%= @maquina.compra %>
                                </p>
                                <p>
                                <strong>Quebrada:</strong>
                                <%= @maquina.quebrada %>
                                </p>
                                <div>
                                    <%= link_to 'Alterar', edit_maquina_path(@maquina), class:"btn btn-warning" %> 
                                    <%= link_to 'Voltar', maquinas_path, class:"btn btn-info" %> 
                                </div>
                            </div>
                        </div>
                </section>
            </main>
        </div>
    </div>
</div>
  